import type { Metadata, Viewport } from "next";
import "./globals.css";
import {
  ClerkProvider,

} from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"
import {Providers} from "./providers";
import { ViewTransitions } from "next-view-transitions";

export const metadata: Metadata = {
  title: {
    default: 'watchparty',
    template: '%s --- watchparty',
  },
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/experimental12.svg" },
      { url: "/experimental12.svg", sizes: "16x16", type: "image/png" },
      { url: "/experimental12.svg", sizes: "32x32", type: "image/png" },
    ],
    apple: [
      { url: "/experimental12.svg", sizes: "180x180" }
    ],
  },
  appleWebApp: {
    title: "watchparty",
    statusBarStyle: "default",
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark
      }}
    >
      <ViewTransitions>
      <html lang="en" className="hidden-scrollbar">
        <body className="hidden-scrollbar">
        <Providers>
          <ThemeProvider
            attribute="class"
            storageKey="BRtheme"
          >
            <Toaster theme="light" position="bottom-center"/>
            {children}
          </ThemeProvider>
          </Providers>
        </body>
      </html>
      </ViewTransitions>
    </ClerkProvider>
  );
}